# Generated by Django 5.0.3 on 2024-03-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('value', models.FloatField(verbose_name='Amount of money')),
                ('created_at', models.DateTimeField(verbose_name='Perform date & time')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
            },
        ),
    ]
